### ISSUE TITLE
--no-resample option is broken

### ISSUE THREAD

**Issue by jburzy** [umami-hep/umami-preprocessing#17]
Hello! 

I believe that there is an issue with the `--no-resample` option. If I try a fresh processing with the `--no-resample` option, and `--split=all`, I get the following error during the `train` sample preparation:
```
INFO     ----------------------------------------- Running Merging ------------------------------------------
Traceback (most recent call last):
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/env/bin/preprocess", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/main.py", line 100, in main
    run_pp(args)
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/main.py", line 69, in run_pp
    merging.run()
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/stages/merging.py", line 107, in run
    self.write_components(sample, comps)
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/stages/merging.py", line 58, in write_components
    c.setup_reader(batch_size, fname=c.out_path)
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/classes/components.py", line 30, in setup_reader
    self.reader = H5Reader(fname, batch_size, equal_jets=self.equal_jets, jets_name="vertices",**kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 12, in __init__
  File "/project/6024950/jburzyns/Tracking/HSSelection/atlas-ftag-tools/ftag/hdf5/h5reader.py", line 184, in __post_init__
    self.readers = [
                   ^
  File "/project/6024950/jburzyns/Tracking/HSSelection/atlas-ftag-tools/ftag/hdf5/h5reader.py", line 185, in <listcomp>
    H5SingleReader(
  File "<string>", line 10, in __init__
  File "/project/6024950/jburzyns/Tracking/HSSelection/atlas-ftag-tools/ftag/hdf5/h5reader.py", line 31, in __post_init__
    self.sample = Sample(self.fname)
                  ^^^^^^^^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "/project/6024950/jburzyns/Tracking/HSSelection/atlas-ftag-tools/ftag/sample.py", line 23, in __post_init__
    raise FileNotFoundError(f"The following files do not exist: {missing}")
FileNotFoundError: The following files do not exist: ['/project/ctb-stelzer/jburzyns/Tracking/HSSelection/DatasetDumper/run/components/train/inclusive_ttbar_hsvertex.h5']
```

If I run first without `--no-resample`, and then try to run with `--no-resample`, this error goes away, but then I get a new error during the `val` sample preparation:

```
INFO     ----------------------------------------- Running Merging ------------------------------------------
Traceback (most recent call last):
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/env/bin/preprocess", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/main.py", line 100, in main
    run_pp(args)
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/main.py", line 69, in run_pp
    merging.run()
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/stages/merging.py", line 107, in run
    self.write_components(sample, comps)
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/stages/merging.py", line 73, in write_components
    self.writer.add_attr("unique_jets", components.unique_jets)
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/classes/components.py", line 173, in unique_jets
    return sum(c.unique_jets for c in self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/classes/components.py", line 173, in <genexpr>
    return sum(c.unique_jets for c in self)
               ^^^^^^^^^^^^^
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/classes/components.py", line 92, in unique_jets
    return sum([r.get_attr("unique_jets") for r in self.reader.readers])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/upp/classes/components.py", line 92, in <listcomp>
    return sum([r.get_attr("unique_jets") for r in self.reader.readers])
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6024950/jburzyns/Tracking/HSSelection/atlas-ftag-tools/ftag/hdf5/h5reader.py", line 45, in get_attr
    return obj.attrs[name]
           ~~~~~~~~~^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/project/6024950/jburzyns/Tracking/HSSelection/umami-preprocessing/env/lib/python3.11/site-packages/h5py/_hl/attrs.py", line 56, in __getitem__
    attr = h5a.open(self._id, self._e(name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 80, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'unique_jets')"
```

I investigated in the code a bit but couldn't find an obvious bug myself. Any help would be appreciated!

**Comment by samvanstroud** [comment]
Hi @jburzy, thanks for the question 👍 

There might be some confusion around the `--no-resample` option. This (and the other CLI flags) are for turning off and on stages in the pipeline. However none of the stages are optional if you are running from scratch (even if you don't want resampling). They are indended for example to be able to re-run later stages after tweaks have been made to the code/config, to avoid running the full pipeline from scratch.

If you want to run without resampling, you instead need to change your config as follows:

```yaml
resampling:
  method: none 
```

The "resampling stage" is still necessary in this case, but no actual resampling will be performed.

Hope that helps!

**Comment by jburzy** [comment]
Hi @samvanstroud, 

Apologies for the silly question, thank you for clarifying! I confirm that the `method: none` option does the trick for me. Cheers!
